services:

    calculators.softwareshinobi.online:

        container_name: calculators.softwareshinobi.online
        
        image: softwareshinobi/calculators.softwareshinobi.online

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: unless-stopped

        ports:

            - 8000:80
