services:

    calculators.softwareshinobi.com:

        container_name: calculators.softwareshinobi.com
        
        image: softwareshinobi/calculators.softwareshinobi.com

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: unless-stopped

        ports:

            - 8000:80
